---
# tasks/install_containerd.yml
- name: Install containerd
  apt:
    name: containerd
    state: present

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd config
  command: containerd config default
  register: containerd_config

- name: Write containerd config
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml

- name: Enable SystemdCgroup in containerd config
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^\s*SystemdCgroup\s*='
    line: '            SystemdCgroup = true'

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes

- name: Enable containerd service
  systemd:
    name: containerd
    enabled: yes
